import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from 'next/image';
import { Button } from "react-bootstrap";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout(props: RootLayoutProps) {

  const today = new Date();

  const dateFormat = `${today.getFullYear()}年${String(today.getMonth() + 1)}月${String(today.getDate())}日`

  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="firstSection">
            <div>
              <Image
                src="/rostergo10.webp"
                alt="RosterGo"
                width={250}
                height={250}
              />
            </div>
            <div className="userActions">
              <div>{dateFormat}</div>
              <div><Button>Change Password</Button></div>
              <div><Button>Logout</Button></div>
            </div>

          </div>

          <div>
            <h1>Daily Status</h1>
          </div>

          <div>
            {props.children}
          </div>
        </div>

      </body>
    </html>
  )

}
