import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from 'next/image';
import { Button } from "react-bootstrap";
import Link from "next/link"
import styles from './page.module.scss'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout(props: RootLayoutProps) {

  const today = new Date();

  const dateFormat = `${today.getFullYear()}年${String(today.getMonth() + 1)}月${String(today.getDate())}日`

  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="firstSection">
            <div>
              <Link href="/">
              <Image
                src="/rostergo10_final_transparent.png"
                alt="RosterGo"
                width={100}
                height={100}
              /> </Link>
            </div>
            <div className="userActions">
              <div>{dateFormat}</div>
              <div><Button>Change Password</Button></div>
              <div><Button>Logout</Button></div>
            </div>

          </div>

          <nav className={styles.navbar}>
              <Link href="/">
                Daily Status
                </Link>
                <Link href="/roster" className="px-3 py-2 rounded-md hover:bg-gray-100">
                  Roster
                </Link>
                <Link href="/employee" className="px-3 py-2 rounded-md hover:bg-gray-100">
                  Employee
                </Link>
                <Link href="/branch" className="px-3 py-2 rounded-md hover:bg-gray-100">
                  Branch
                </Link>
                <Link href="/shift" className="px-3 py-2 rounded-md hover:bg-gray-100">
                 Shift Slot
                </Link>
          
            {/* <h1>Daily Status</h1> */}
          </nav>

          <div>
            {props.children}
          </div>
        </div>

      </body>
    </html>
  )

}
